Update Replit README.md
AnswerDotAI/fh-deploy pull request #4
Opened 2024-08-06 21:30 UTC by mattppal

This PR updates the instructions for getting started with Replit, specifically by being more descriptive about how to configure, deploy, and customize a Repl. Screenshots were added where useful. 

I also linked to an additional example and provided relevant background on Replit to help users understand other services that might enhance their FastHTML app.

2024-08-06 21:31 UTC, mattppal commented
@jph00 can't add you as a reviewer, so tagging here :)

2024-08-07 03:10 UTC, jph00 requested changes
Thank you! Main issue is fixing the image. Also remove language that makes uncited claims, is marketing-oriented, or makes claim of ease/simplicity (the latter is because such claims can leave users feeling intimidated or stupid if they don't find it easy).

2024-08-07 03:10 UTC, jph00 commented on replit/README.md
> +It comes with handy tools, like [secrets management](https://docs.replit.com/programming-ide/storing-sensitive-information-environment-variables) and [AI assisted coding](https://docs.replit.com/prog
```suggestion
It comes with tools like [secrets management](https://docs.replit.com/programming-ide/storing-sensitive-information-environment-variables) and [AI assisted coding](https://docs.replit.com/programming-ide/ai-code-completion), and has good Python, JS, HTML, and CSS support for FastHTML apps. Replit also has cloud services like [object storage](https://docs.replit.com/storage/replit-database), [embedded Postgres](https://docs.replit.com/hosting/databases/postgresql-database), and [key-value databases](https://docs.replit.com/hosting/databases/replit-database).
```

2024-08-07 03:10 UTC, jph00 commented on replit/README.md
> +   <img src="https://github.com/user-attachments/assets/dd50c381-4319-4960-87da-b5b5566b49c3" width="75%"/>
This is a streamlit example! :O

2024-08-07 03:10 UTC, jph00 commented on replit/README.md
> +To get started on Replit, follow these easy steps:
```suggestion
To get started on Replit, follow these steps:
```

2024-08-07 03:10 UTC, jph00 commented on replit/README.md
> +A web view pane will open up with your application. Simply edit the code in the editor to see changes in real time.
```suggestion
A web view pane will open up with your application. Edit the code in the editor to see changes in real time.
```

2024-08-07 03:10 UTC, jph00 commented on replit/README.md
> +Deployment on Replit is straightforward and can be done in a few steps:
```suggestion
Deployment on Replit can be done in a few steps:
```

2024-08-07 03:10 UTC, jph00 commented on replit/README.md
> +   - For frontend apps, select "Autoscale" deployments. These are cost-effective and automatically scale based on traffic.
```suggestion
   - For frontend apps, select "Autoscale" deployments. These automatically scale based on traffic.
```

2024-08-07 19:28 UTC, mattppal commented
Made some changes @jph00, thank you for your feedback

2024-08-07 20:18 UTC, merged

2024-08-07 20:19 UTC, jph00 commented
Thanks! What's a good way for us to collaborate on a template for this? Currently @comhar owns the template, but it would probably make more sense for replit to own it and make us collaborators?

2024-08-07 21:32 UTC, mattppal commented
@jph00 we recommend that partners own their templates. 

We could get you set up with a Public profile that would serve as a "homepage" of sorts, e.g. https://replit.com/@weaviate

2024-08-07 22:20 UTC, jph00 commented
That sounds great!

> Message ID: ***@***.***>
>

2024-08-08 01:55 UTC, jph00 commented
Our team account is replit.com/t/answerai BTW.

2024-08-08 15:46 UTC, mattppal commented
@jph00 will dm you on X for next steps